### ISSUE TITLE
No longer able to send torrent to server with context menu.

### ISSUE THREAD

**Issue by ASympathy** [sbussetti/deluge-siphon#18]
This site used to require that I use the context menu to send to deluge, despite any settings of left-click handling, but now I'm getting an error when I do it that way.

It says to check the console for the error message, but it wasn't something I was able to figure out without direction. I assume posting the site here is not recommended. If you could advise on how to provide a log file, I would be happy to do so.

**Comment by sbussetti** [comment]
Which site?  It's possible the site has changed the way they handle torrents.

**Comment by ASympathy** [comment]
nyaa.eu
Below is what I use as a shortcut:
http://www.nyaa.eu/?page=search&cats=0_0&filter=0&term=%5BHorrible+Subs%5D

**Comment by ASympathy** [comment]
Have you been able to identify the issue, or is there anything that I can do on my end to resume using deluge-siphon?

Thanks for your time.

**Comment by ASympathy** [comment]
So, is this resolved now?

**Comment by sbussetti** [comment]
Sorry for not commenting!  I was just going through old issues and closing them out.  I successfully sent a link to my deluge server using the context menu on the site in the link provided above.  I just right clicked on the [v] download icon, selected "Send to Deluge" and everything works fine.

I can't reproduce your issue but maybe it was fixed in a previous version.

**Comment by ASympathy** [comment]
I was just able to confirm it's working for me now too, including for left-click handling. Thanks!
