### ISSUE TITLE
Connection manager set to Pi Host can't add torrent.

### ISSUE THREAD

**Issue by shanep2300** [sbussetti/deluge-siphon#27]
Hello,

I can't right click and send to deluge if connect to the Pi host. But if I drag the torrent into the WebUI, the window client opens and downloads just fine. 

If I switch the connection host to the local IP, 127.0.0.1, then right clicking on a torrent is sent to the deluge web just fine.

**Comment by sbussetti** [comment]
can you give me an example of the "Deluge Server URL" you are using for your Pi?

**Comment by shanep2300** [comment]
Deluge Server URL: http://192.168.1.121:8112
Connection Manager Host: 192.168.1.121:58846

**Comment by sbussetti** [comment]
My extension only talks to the web-ui.  Unless you have configured it otherwise, deluged only listens on localhost for connections from deluge-web.  If you are running deluge-web on one host, and deluged on another host, you need to ensure that deluged on  that other host is listening on  a public interface.

**Comment by shanep2300** [comment]
Unfortunately, you lost me... I think deluge-web and deluged should be both
running from the Pi. If I'm understanding you correctly, there is something
wrong on my end causing the right click from deluge-siphon to not work and
the deluge-web force opening the windows client if the torrent is dragged
and dropped onto deluge-web.

**Comment by sbussetti** [comment]
This isn't a problem with my extension.  If deluge-web and deluged are both running on the same server, your host in connection manager *should* be 127.0.0.1

**Comment by sbussetti** [comment]
Lastly, you can't drag and drop torrents into the deluge-web ui -- what is happening when you do that, is that your browser is opening the file locally based on the file-type associations your OS has.  Since you also have deluge installed on  your local box, it tries to open it -- again not a problem with my extension.
