### ISSUE TITLE
Stopped working after recent update

### ISSUE THREAD

**Issue by shidraconis** [sbussetti/deluge-siphon#76]
It now gives me a windows notification (which is good) with the message "Enable this is Preferences -> Dameon"   Remote connections must be allowed. 
It does this when trying to send a torrent/magnet link to my deluge server.  Not just right click and add to deluge but also the simple left click on a link. Under the DevTools for chrome extensions console tab it shows: "background.min.js:6 _getServerConfig__error Remote connections disabled"

**Comment by sbussetti** [comment]
Did you try enabling that setting in deluge?

**Comment by shidraconis** [comment]
Well, now I feel stupid, that was it, not sure why that got turned off, but whatever, thanks.

**Comment by Luke9090** [comment]
I nearly posted a duplicate of this issue (new to Github, didn't spot the option to view "closed" issues straight away).
ChromeOS seems to truncate that error message so all I was getting was "Enable this in Preferences -> Daemon".
![screenshot 2019-01-11 at 21 29 54](https://user-images.githubusercontent.com/46611362/51061245-8f2afb00-15ea-11e9-9078-b1b61351e9d9.png)

If there's any way to work around that truncated error message, you might get less people bugging you about it. I was confused by the need to change Daemon-related settings anyway because I thought delugesiphon accessed Deluge through the WebUI. Has the new update changed the access method?

While I'm commenting, thanks for your work on this, it's a really handy extension!
